name: Static Analysis

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Nix
        uses: cachix/install-nix-action@v31

      - name: lint
        run: nix develop --impure -c just lint

      - name: format
        run: nix develop --impure -c just format
